import {selectAnatomy} from '@ark-ui/react/select';
import {tv} from 'tailwind-variants';
import {anatomyToRecipeSlots} from '~/utils/anatomyToRecipeSlots';

export const selectRecipe = tv({
	slots: anatomyToRecipeSlots(selectAnatomy, {
		control: 'flex gap-2',
		trigger: [
			'h-11',
			'px-4',
			'grow',
			'flex',
			'items-center',
			'rounded-lg',
			'border',
			'bg-neutral-900',
			'ui-invalid:border-red-400',
			'ui-invalid:focus-within:outline-red-400',
			'focus:outline-2',
			'focus:outline-solid',
			'focus:outline-emerald-600',
			'focus:-outline-offset-1',
			'ui-open:ui-invalid:border-red-400',
			'ui-open:ui-invalid:outline-red-400',
		],
		valueText: 'grow text-left',
		indicator: [
			'size-5',
			'text-neutral-300',
			'transition-transform',
			'duration-300',
			'ui-open:rotate-180',
			'ui-closed:rotate-0',
		],
		positioner: 'z-dropdown',
		content: [
			'z-dropdown',
			'max-h-(--available-height)',
			'overflow-y-auto',
			'rounded-lg',
			'border',
			'border-neutral-700',
			'bg-neutral-800',
			'focus-visible:outline-2',
			'focus-visible:outline-offset-2',
			'focus-visible:outline-white/50',
			'p-1',

			'ui-placement-bottom:ui-open:animate-popover-in-bottom',
			'ui-placement-bottom-start:ui-open:animate-popover-in-bottom',
			'ui-placement-bottom-end:ui-open:animate-popover-in-bottom',
			'ui-placement-bottom:ui-closed:animate-popover-out-bottom',
			'ui-placement-bottom-start:ui-closed:animate-popover-out-bottom',
			'ui-placement-bottom-end:ui-closed:animate-popover-out-bottom',

			'ui-placement-top:ui-open:animate-popover-in-top',
			'ui-placement-top-start:ui-open:animate-popover-in-top',
			'ui-placement-top-end:ui-open:animate-popover-in-top',
			'ui-placement-top:ui-closed:animate-popover-out-top',
			'ui-placement-top-start:ui-closed:animate-popover-out-top',
			'ui-placement-top-end:ui-closed:animate-popover-out-top',

			'ui-placement-left:ui-open:animate-popover-in-left',
			'ui-placement-left-start:ui-open:animate-popover-in-left',
			'ui-placement-left-end:ui-open:animate-popover-in-left',
			'ui-placement-left:ui-closed:animate-popover-out-left',
			'ui-placement-left-start:ui-closed:animate-popover-out-left',
			'ui-placement-left-end:ui-closed:animate-popover-out-left',

			'ui-placement-right:ui-open:animate-popover-in-right',
			'ui-placement-right-start:ui-open:animate-popover-in-right',
			'ui-placement-right-end:ui-open:animate-popover-in-right',
			'ui-placement-right:ui-closed:animate-popover-out-right',
			'ui-placement-right-start:ui-closed:animate-popover-out-right',
			'ui-placement-right-end:ui-closed:animate-popover-out-right',
		],
		item: [
			'flex',
			'w-full',
			'cursor-pointer',
			'items-center',
			'gap-2',
			'rounded-md',
			'px-3',
			'py-2',
			'text-sm',
			'text-neutral-300',
			'transition-colors',
			'duration-200',
			'ui-disabled:cursor-not-allowed',
			'ui-disabled:opacity-65',
			'ui-highlighted:bg-neutral-700/25',
			'icon:size-4',
			'icon:text-neutral-300',
		],
		itemText: 'grow',
		itemIndicator: 'flex size-5 text-emerald-500!',
	}),
});
